RightTyper/RightTyper

righttyper/righttyper.py
righttyper/righttyper_shapes.py
righttyper/righttyper_types.py

Backed out new sampling algorithm for now, as the previous (new) algorithm caused unacceptably high overheads. Will revisit. Also fixes some bugs.
---

Back to the future

---

righttyper/righttyper_tool.py

Minor code cleanup

---

README.md
pyproject.toml
righttyper/righttyper.py
righttyper/righttyper_shapes.py
righttyper/righttyper_tool.py
righttyper/righttyper_utils.py

Major changes:
* Incorporated an adaptive sampling approach. Tracks overhead by sampling the stack and checking to see when we are in instrumentation code. RightTyper puts off restarting instrumentation if need be until it falls below the target threshold (by default, 5%).
Minor changes:
* Added `--infer-shapes` flag (off by default).
* Added `[shapes]` optional dependency for installations
* Weakened dependencies and moved some out to optional dependency above
---

Adaptive sampling

---

righttyper/righttyper.py

Optimizes the inference of instrumented vs. non-instrumented execution balance by checking code (instead of function name & filename).
---

Match code instead of names

---

righttyper/righttyper_runtime.py

Handles libraries that use dtypes (notably numpy).
---

Dtype handling

---

righttyper/righttyper_process.py
righttyper/unified_transformer.py

*Issue #, if available:*
Testing to see if unifying the transformers improves performance.
----

Unified transformer [WIP]

---

README.md

Fixed typo and coloration

---

righttyper/annotation_coverage.py
righttyper/get_import_details.py
righttyper/replace_dicts.py
righttyper/righttyper.py
righttyper/righttyper_process.py
righttyper/righttyper_utils.py
righttyper/unified_transformer.py

Adding annotations to reduce mypy complaints.
---

Mypy compliance

---

righttyper/random_dict.py
righttyper/replace_dicts.py
righttyper/unified_transformer.py
righttyper/util/classify-mypy-errors.py

Moar types

---

righttyper/unified_transformer.py
tests/test_transformer.py

Alternative way to emit imports, based on type names

---

righttyper/unified_transformer.py
tests/test_transformer.py

Fixed bug handling locally defined types.

---

righttyper/unified_transformer.py
tests/test_transformer.py

Fixed transformer not applying changes to methods

---

righttyper/righttyper_runtime.py
righttyper/unified_transformer.py
tests/test_integration.py
tests/test_typing.py

Greatly improving support for 'builtins' types;

---

righttyper/righttyper_runtime.py
tests/test_integration.py

Added full qualification of inner type in `dtype`

---

.github/workflows/tests.yml

Adding CI for tests

---

righttyper/righttyper.py
righttyper/righttyper_process.py
righttyper/righttyper_runtime.py
righttyper/unified_transformer.py
tests/test_integration.py
tests/test_transformer.py
tests/test_typing.py

- adds support for local classes and local functions;
- adds async generator detection;
- adds function default values processing, annotating e.g. a `=None` parameter `Optional[...]`;
- fixes numerous `builtins` function typing;
- fixes typing for inner classes;
- fixes local alias search, which failed depending on stack depths;
- aligns `Generator` and `AsyncGenerator` types given as parameter and return values;
- makes `Self` detection more reliable;
- allows disabling use of multiprocessing (to facilitate testing);
- adds numerous tests;

Support for local classes and functions among others;

---

righttyper/righttyper.py
righttyper/righttyper_process.py
righttyper/righttyper_runtime.py
righttyper/righttyper_types.py
righttyper/righttyper_utils.py
righttyper/unified_transformer.py
tests/test_integration.py
tests/test_transformer.py

Handles import name conflicts, fixes bugs finding modules, some cleanups

---

righttyper/righttyper.py
righttyper/righttyper_process.py
righttyper/righttyper_runtime.py
righttyper/righttyper_types.py
righttyper/righttyper_utils.py
righttyper/unified_transformer.py
tests/test_integration.py
tests/test_transformer.py
tests/test_typing.py

Fixed sampling from dict when its items() method doesn't return a Collection and a few other things

---

righttyper/generate_stubs.py
righttyper/random_dict.py
righttyper/righttyper.py
righttyper/righttyper_runtime.py
righttyper/righttyper_tool.py
righttyper/unified_transformer.py
righttyper/util/classify-mypy-errors.py
tests/test_stubs.py
tests/test_transformer.py
tests/test_typing.py

Bug fixes, cleanup

---

righttyper/righttyper.py
righttyper/righttyper_runtime.py
righttyper/unified_transformer.py
tests/test_integration.py
tests/test_typing.py

Added support for keyword-, positional-only, args and kwargs arguments; added searching package for types

---

righttyper/annotation_coverage.py

In some edge cases (`sympy/polys/numberfields/resolvent_lookup.py`), parsing the AST leads to a stack overflow. This PR reduces this risk by geometrically increasing the recursion limit twofold on each failure.

Adaptively increase recursion limit when necessary.

---

pyproject.toml
righttyper/righttyper.py

Temporary work-around to argument processing issue.
----

Arg processing fix

---

righttyper/righttyper.py
righttyper/righttyper_process.py
righttyper/righttyper_runtime.py
righttyper/righttyper_types.py
righttyper/righttyper_utils.py
righttyper/unified_transformer.py
tests/test_integration.py
tests/test_transformer.py

Improved Generator/Iterator typing, bug fixes, cleanups

---

righttyper/righttyper.py
righttyper/righttyper_process.py
righttyper/righttyper_runtime.py
righttyper/righttyper_utils.py
righttyper/unified_transformer.py
tests/test_integration.py
tests/test_transformer.py
tests/test_typing.py

Improved "Self" recognition, fixed circular frame references, move to generate righttyper.out from transformer, DRYing code

---

righttyper/righttyper.py

Switch to SimpleQueue, small code cleanups

---

righttyper/righttyper.py
righttyper/righttyper_process.py

Reimplement multiprocessing with concurrent.futures.ProcessPoolExecutor.

---

.github/workflows/smoketests.yml
.github/workflows/tests.yml
pyproject.toml
righttyper/righttyper.py
righttyper/righttyper_runtime.py
tests/test_integration.py
tests/test_typing.py

Adding "smoke test" workflow and several bug fixes.

---

righttyper/righttyper.py
righttyper/righttyper_process.py
righttyper/righttyper_runtime.py
righttyper/righttyper_types.py
righttyper/righttyper_utils.py
tests/test_integration.py
tests/test_typing.py

Added support for Callable typing based on discovered types

---

righttyper/righttyper.py
righttyper/righttyper_process.py
righttyper/righttyper_runtime.py
righttyper/righttyper_types.py
righttyper/righttyper_utils.py
righttyper/unified_transformer.py
tests/test_integration.py
tests/test_typing.py

Implemented union of generics' arguments, reimplemented superclass search, fixed a few bugs

---

.github/workflows/tests.yml

Bump test version.

---

righttyper/righttyper.py

*Issue #, if available:*
N/A
Added a try/finally block around the target script execution code to gracefully handle errors.
Also generates types if errors are thrown.

Added correct event cleanup

---

righttyper/righttyper.py
righttyper/righttyper_process.py
righttyper/righttyper_runtime.py
righttyper/righttyper_types.py
righttyper/righttyper_utils.py
righttyper/unified_transformer.py
tests/test_tool.py
tests/test_transformer.py

Mostly innocuous changes to mollify ruff.
---

Ruff-suggested fixes.

---

righttyper/righttyper.py
righttyper/righttyper_runtime.py

Small fixes

---

README.md
righttyper/righttyper.py

Reorganized and fixed type coverage options

---

README.md
righttyper/righttyper.py
righttyper/typeinfo.py
tests/test_typeinfo.py

(Re-)added array shape generalization, made --sampling / --no-sampling public

---

righttyper/righttyper.py
righttyper/righttyper_runtime.py
righttyper/righttyper_types.py
righttyper/typeinfo.py
righttyper/unified_transformer.py
tests/test_integration.py
tests/test_typing.py

*Issue #, if available:*
#71
*Description of changes*
Adds code to recognize method calls and correctly labels arguments and return values with `Self`

Smarter Typing for `Self`

---

righttyper/righttyper.py
righttyper/righttyper_types.py
righttyper/typeinfo.py
tests/test_transformer.py
tests/test_typeinfo.py
tests/test_typing.py

MyPy fixes, cleanups

---

.github/workflows/release.yml
.github/workflows/tests.yml
.gitignore
righttyper/righttyper.py
righttyper/righttyper_process.py
righttyper/righttyper_runtime.py
righttyper/righttyper_types.py
righttyper/traverse.cpp
righttyper/unified_transformer.py
setup.py
tests/test_integration.py
tests/test_transformer.py
tests/test_typing.py

Unfortunately, a workaround for [this likely CPython bug](https://github.com/python/cpython/issues/129013) affecting async generators requires a C API module.

Greatly improves Generator, AsyncGenerator and Coroutine typing

---

righttyper/righttyper.py
righttyper/righttyper_utils.py

Attempts to harden code against the errors shown in issue #93;

---

tests/test_integration.py

Adds missing test fixture

---

righttyper/ast_instrument.py
righttyper/loader.py
righttyper/random_dict.py
righttyper/replace_dicts.py
righttyper/righttyper.py
righttyper/righttyper_runtime.py
tests/test_ast_instrument.py
tests/test_integration.py

Prepares to reintegrate RandomDict, fixes pytest instrumentation and some small issues.

---

righttyper/typeinfo.py
tests/test_typing.py

(mostly) fixed bug finding unsuitable superclasses

---

.github/workflows/codeql.yml
.github/workflows/release.yml
pyproject.toml
setup.py

Adjusted release workflow given C++ based Python bug workaround

---

righttyper/typeinfo.py
tests/test_typeinfo.py
tests/test_typing.py

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution under the terms of your choice.

Removed "similar generics" merging, which could yield incorrect results;

---

righttyper/righttyper.py
righttyper/righttyper_types.py
tests/test_integration.py

Fixes discovered Callable types, which included varargs and kwargs arguments.

---

righttyper/ast_instrument.py
righttyper/loader.py
righttyper/righttyper.py
tests/test_ast_instrument.py
tests/test_integration.py

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution under the terms of your choice.

Added '--replace-dict', making replacing 'dict' with RandomDict a runtime option;

---

pyproject.toml
righttyper/righttyper_runtime.py
righttyper/typeinfo.py
tests/conftest.py
tests/test_integration.py
tests/test_typing.py

Improved supertype search and type set merging, fixes some bugs

---

righttyper/righttyper_runtime.py
tests/test_integration.py
tests/test_typing.py

Improved type name search, improved numpy iterator support, bug fixes.

---

righttyper/righttyper.py
righttyper/righttyper_runtime.py
righttyper/righttyper_types.py
tests/test_integration.py

Fixed exception traceback being obscured when using multiprocessing, added test

---

righttyper/righttyper_runtime.py
tests/test_integration.py
tests/test_typing.py

Fixed TypeFinder not finding special definitions from "typing"

---

righttyper/righttyper.py
righttyper/righttyper_runtime.py
tests/test_integration.py
tests/test_typing.py

Fixes missing support for MappingProxyType, moves inconsistent samples messages to logfile, cleanups

---

righttyper/loader.py
righttyper/options.py
righttyper/righttyper.py
righttyper/righttyper_runtime.py
righttyper/righttyper_types.py
righttyper/typeinfo.py
tests/test_integration.py
tests/test_typing.py

Greatly improves performance, implements call trace filtering, fixes bug emitting annotations for 3.9 and few other issues

---

righttyper/righttyper_runtime.py
righttyper/righttyper_types.py
tests/test_integration.py
tests/test_typing.py

Fixed attribute error bugs, added handling for Literal when converting type hints

---

README.md

Adds more badges to README

---

righttyper/typeinfo.py
tests/test_integration.py

*Issue #, if available:*
#88 
Add implementation of [PEP 3141](https://peps.python.org/pep-3141/) to type merging code

Numeric tower implementation

---

README.md

Added paper link to README

---

README.md

Described --type-depth-limit in README

---

righttyper/righttyper.py
righttyper/righttyper_runtime.py

Improved debug logging

---

README.md
righttyper/options.py
righttyper/righttyper.py
righttyper/righttyper_runtime.py
righttyper/righttyper_utils.py

Added --no-sampling-for

---

righttyper/options.py
righttyper/righttyper.py
righttyper/righttyper_runtime.py
righttyper/typemap.py
tests/test_integration.py
tests/test_typing.py

Revamped type name canonicalization map; avoid test names in canonical names.
